@startchen

left to right direction

entity User {
}
entity Basket {
}

relationship owns {
}

User -1- owns
owns -1- Basket

entity Product {
}

relationship contains {
    Count
}

Basket -M- contains
contains -N- Product

@endchen
